### ISSUE TITLE
How to use sheets api?

### ISSUE THREAD

**Issue by Buszmen** [wlzla000/googleapis-async#1]
I try `return await google.sheets('v4').spreadsheets.values.get({` but I get Unhandled Rejection:  TypeError: google.sheets(...).spreadsheets.values.get is not a function. Can you help me with some example how to use it with sheets API?

**Comment by wlzla000** [comment]
Thank you for reporting this issue.

I'm so sorry. Unfortunately, it seems a logical bug.
I considered all the API methods to be in `google.A().B.C()` format,
however, it's `google.A().B.C.D()` for some APIs, such as `sheets` that you said.

I'll fix it as soon as possible, but it would take some days.
Thank you for contributing to `googleapis-async` and I'm sorry again.

**Comment by wlzla000** [comment]
Refactoring the code with a fix for the bug has been done,
and I'm currently testing/debugging it.

**Comment by wlzla000** [comment]
Okay, I've just updated it to 2.0.0 version.
Please update it and try it again.

-----

`const google = require("googleapis-async");`

- `google.youtube("v3").liveStreams.insert()`
- `google.sheets("v4").spreadsheets.values.get()`

They should return a `Promise`.

-----

Feel free to leave comments or issues.
